### PR TITLE
fix: miss http body

### PR DESCRIPTION
**Pull request by luoyunhe**
**What type of PR is this?**

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by 00pf00** [comment]
The request of kubectl logs is a Get request, and the request of kubectl exec requires a protocol upgrade. After the protocol upgrade, the data is transmitted through a long connection channel, such as spdy, so the content of the http body is always nil

**Comment by luoyunhe** [comment]
We use tunnel to proxy requests from the cloud to the edge k8s api-server, and found that it cannot proxy post requests.

**Comment by 00pf00** [comment]
image
kubectl log is normal
image
kubectl exec is normal

**Comment by neweyes** [comment]
Sorry to tell you, the main branch is temporarily frozen because the CI process is being built. Before the CI is ready, please submit PR based on the latest release, which is currently release-0.2

**Comment by luoyunhe** [comment]
ok

**Pull request closed without merging**
